# Generated by Django 4.1.2 on 2022-11-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accounts_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='group_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
